default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: postgres
  timeout: 5000
  reaping_frequency: 30
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_hirer_development
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *default
  database: api_hirer_test
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: api_hirer_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
